apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: auto_chef:latest  # Replace with your local image name and tag
        imagePullPolicy: Never    # Use the local image; do not attempt to pull
        ports:
        - containerPort: 6996
